// settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        mavenCentral()
    }
}

rootProject.name = 'fmmod' // 确保这行在 pluginManagement 之后